name = "abtest"
# type = "javascript" is required to use the `[build]` section
type = "javascript"
workers_dev = true
account_id = "078a5f55b1012df45f460af4d5ab1e9a"
compatibility_date = "2022-02-17"

[build.upload]
dir = "./"
format = "modules"
main = "./abtest.js"

[durable_objects]
bindings = [{name = "AB_VARIANT_SWITCH", class_name = "ABVariantSwitch"}]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["ABVariantSwitch"]
